### ISSUE TITLE
How to integrate this code with keycloak?

### ISSUE THREAD

**Issue by clabnet** [patrickpissurno/fastify-esso#20]
Hello, 
I have a running local instance of keycloak server and one Fastify microservice with REST APIs. 
I need to authenticate these routes with token produced by keycloak.
Can you tell me please how to verify token created by keycloak on Fastify server using fastify-esso ?
Thanks in advance

**Comment by patrickpissurno** [comment]
So, that's something out of scope for this project. Currently, it only supports validating tokens it generated itself. Adding support for a different generator would increase complexity, so at least for now, it's not something I'm planning to support.

Thanks
